version: "2"
services:
    pgs-api-server:
        build : .
        ports :
        - "8081:8081"
        volumes : 
          - ./server-volume:/code
        links:
            - mongodb:mongodb
        restart: always
        depends_on:
            - mongodb
        networks:
          - webnet
        environment:
          - MONGODB_SERVER_HOST=mongodb
          - MONGODB_SERVER_PORT=27017 
    mongodb:
        # replace username/repo:tag with your name and image details
        container_name: mongodb
        image: mongo:latest
        ports:
          - "27017:27017"
        restart: always
        volumes:
            - ./data:/data/db # the data repository to save the files from the mongodb
        networks:
          - webnet
networks:
  - webnet

        